# Site settings
baseurl = "http://devopsmodel.com/"
languageCode = "en-us"
title = "DevOps Model - One Stop Shop for DevOps reference material"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXXXXX-Y"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "DevOps Model - One Stop Shop for DevOps reference material"
    subtitle = "The place where you can find anything and everything about DevOps"
    author = "School of DevOps"
    description = "Hugrid - grid theme for Hugo with an expanding image preview."
    keywords = "DevOps, School, of"

    # Body background color
	bodybgcolor = "#f9f9f9"

    # Preview container button text
    buttontext = "Click here!"

    # Footer text
    footertext = "Made by [School of DevOps](http://schookofdevops.com/)"
